// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: campaignplan.sql

package db

import (
	"context"
)

const createCampaignPlan = `-- name: CreateCampaignPlan :exec
INSERT INTO CampaignPlans (campaign_id, plan_id)
VALUES ($1, $2)
`

type CreateCampaignPlanParams struct {
	CampaignID int32 `json:"campaign_id"`
	PlanID     int32 `json:"plan_id"`
}

func (q *Queries) CreateCampaignPlan(ctx context.Context, arg CreateCampaignPlanParams) error {
	_, err := q.db.ExecContext(ctx, createCampaignPlan, arg.CampaignID, arg.PlanID)
	return err
}
