// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Campaign struct {
	CampaignID         int32         `json:"campaign_id"`
	Name               string        `json:"name"`
	Description        string        `json:"description"`
	Code               string        `json:"code"`
	StartDate          time.Time     `json:"start_date"`
	EndDate            time.Time     `json:"end_date"`
	MaxVouchers        int32         `json:"max_vouchers"`
	RedeemedVouchers   sql.NullInt32 `json:"redeemed_vouchers"`
	VoucherLifetime    int32         `json:"voucher_lifetime"`
	DiscountPercentage int32         `json:"discount_percentage"`
	CreatedAt          sql.NullTime  `json:"created_at"`
	UpdatedAt          sql.NullTime  `json:"updated_at"`
}

type Campaignplan struct {
	CampaignID int32 `json:"campaign_id"`
	PlanID     int32 `json:"plan_id"`
}

type Plan struct {
	PlanID   int32  `json:"plan_id"`
	PlanName string `json:"plan_name"`
	Price    string `json:"price"`
}

type Purchase struct {
	PurchaseID      int32         `json:"purchase_id"`
	UserID          sql.NullInt32 `json:"user_id"`
	VoucherID       sql.NullInt32 `json:"voucher_id"`
	PlanID          sql.NullInt32 `json:"plan_id"`
	Amount          string        `json:"amount"`
	DiscountApplied sql.NullBool  `json:"discount_applied"`
	PurchaseDate    sql.NullTime  `json:"purchase_date"`
}

type User struct {
	UserID           int32         `json:"user_id"`
	Name             string        `json:"name"`
	Email            string        `json:"email"`
	PasswordHash     string        `json:"password_hash"`
	RegistrationDate sql.NullTime  `json:"registration_date"`
	LastLogin        sql.NullTime  `json:"last_login"`
	UserTypeID       int32         `json:"user_type_id"`
	PlanID           sql.NullInt32 `json:"plan_id"`
}

type Usertype struct {
	UserTypeID int32  `json:"user_type_id"`
	TypeName   string `json:"type_name"`
}

type Voucher struct {
	VoucherID  int32        `json:"voucher_id"`
	UserID     int32        `json:"user_id"`
	CampaignID int32        `json:"campaign_id"`
	Code       string       `json:"code"`
	ValidUntil time.Time    `json:"valid_until"`
	IsRedeemed sql.NullBool `json:"is_redeemed"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
