// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: campaign.sql

package repository

import (
	"context"
	"time"
)

const isCampaignValid = `-- name: IsCampaignValid :one
SELECT EXISTS (
            SELECT 1 
            FROM Campaigns 
            WHERE code = $1 AND end_date >= $2) isValid
`

type IsCampaignValidParams struct {
	Code    string    `json:"code"`
	EndDate time.Time `json:"end_date"`
}

func (q *Queries) IsCampaignValid(ctx context.Context, arg IsCampaignValidParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isCampaignValid, arg.Code, arg.EndDate)
	var isvalid bool
	err := row.Scan(&isvalid)
	return isvalid, err
}

const isCampaignValidForVoucherGeneration = `-- name: IsCampaignValidForVoucherGeneration :one
SELECT EXISTS (
            SELECT 1 
            FROM Campaigns 
            WHERE code = $1 
            AND end_date > NOW()
            AND redeemed_vouchers < max_vouchers) isValid
`

func (q *Queries) IsCampaignValidForVoucherGeneration(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isCampaignValidForVoucherGeneration, code)
	var isvalid bool
	err := row.Scan(&isvalid)
	return isvalid, err
}
